# -*- coding: utf-8 -*-
"""Project5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZicDRA9ZtSbRaDyF-8PrP2BqLbObFac
"""

# ============================================================
# TELLCO TELECOM ANALYSIS - TASK 1
# Data Loading, Cleaning & User Overview
# ============================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. LOAD DATA
# ------------------------------------------------------------

file_path = "/content/telcom_data (2).xlsx"

df = pd.read_excel(file_path)

print("Data loaded successfully!")
print("Shape:", df.shape)


# ------------------------------------------------------------
# 2. BASIC INFORMATION
# ------------------------------------------------------------

print("\n===== FIRST 5 ROWS =====")
print(df.head())

print("\n===== DATA TYPES =====")
print(df.dtypes)

print("\n===== DATASET INFORMATION =====")
print(df.info())

print("\n===== STATISTICAL SUMMARY =====")
print(df.describe())


# ------------------------------------------------------------
# 3. CHECK DUPLICATES
# ------------------------------------------------------------

print("\n===== DUPLICATES =====")
print("Number of duplicate rows:", df.duplicated().sum())

df = df.drop_duplicates()

print("Shape after removing duplicates:", df.shape)


# ------------------------------------------------------------
# 4. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\n===== MISSING VALUES =====")

missing_values = df.isnull().sum()

missing_values = missing_values[
    missing_values > 0
].sort_values(ascending=False)

print(missing_values)


# ------------------------------------------------------------
# 5. HANDLE MISSING VALUES
# ------------------------------------------------------------

# Numeric columns -> replace missing values with mean

numeric_columns = df.select_dtypes(
    include=np.number
).columns

for column in numeric_columns:
    df[column] = df[column].fillna(
        df[column].mean()
    )


# Categorical columns -> replace missing values with mode

categorical_columns = df.select_dtypes(
    exclude=np.number
).columns

for column in categorical_columns:

    if df[column].isnull().sum() > 0:

        df[column] = df[column].fillna(
            df[column].mode()[0]
        )


print("\nMissing values after treatment:")
print(df.isnull().sum().sum())


# ------------------------------------------------------------
# 6. IDENTIFY NUMERIC COLUMNS
# ------------------------------------------------------------

numeric_columns = df.select_dtypes(
    include=np.number
).columns

print("\n===== NUMERIC COLUMNS =====")
print(list(numeric_columns))


# ------------------------------------------------------------
# 7. OUTLIER TREATMENT
# ------------------------------------------------------------

# According to the project requirement,
# outliers are replaced with the mean.

for column in numeric_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    mean_value = df[column].mean()

    outlier_condition = (
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    )

    number_of_outliers = outlier_condition.sum()

    if number_of_outliers > 0:

        print(
            f"{column}: "
            f"{number_of_outliers} outliers replaced"
        )

        df.loc[
            outlier_condition,
            column
        ] = mean_value


# ------------------------------------------------------------
# 8. CREATE TOTAL TRAFFIC
# ------------------------------------------------------------

df["Total Traffic (Bytes)"] = (
    df["Total DL (Bytes)"] +
    df["Total UL (Bytes)"]
)


# ------------------------------------------------------------
# 9. USER OVERVIEW
# ------------------------------------------------------------

# Aggregate data per customer/MSISDN

user_overview = df.groupby(
    "MSISDN/Number"
).agg(

    sessions=(
        "Bearer Id",
        "count"
    ),

    total_duration=(
        "Dur. (ms)",
        "sum"
    ),

    total_download=(
        "Total DL (Bytes)",
        "sum"
    ),

    total_upload=(
        "Total UL (Bytes)",
        "sum"
    ),

    total_traffic=(
        "Total Traffic (Bytes)",
        "sum"
    )

).reset_index()


# ------------------------------------------------------------
# 10. APPLICATION TRAFFIC
# ------------------------------------------------------------

user_overview["Social Media Traffic"] = (
    df.groupby("MSISDN/Number")[
        "Social Media DL (Bytes)"
    ].sum().values
    +
    df.groupby("MSISDN/Number")[
        "Social Media UL (Bytes)"
    ].sum().values
)


user_overview["Google Traffic"] = (
    df.groupby("MSISDN/Number")[
        "Google DL (Bytes)"
    ].sum().values
    +
    df.groupby("MSISDN/Number")[
        "Google UL (Bytes)"
    ].sum().values
)


user_overview["Email Traffic"] = (
    df.groupby("MSISDN/Number")[
        "Email DL (Bytes)"
    ].sum().values
    +
    df.groupby("MSISDN/Number")[
        "Email UL (Bytes)"
    ].sum().values
)


user_overview["Youtube Traffic"] = (
    df.groupby("MSISDN/Number")[
        "Youtube DL (Bytes)"
    ].sum().values
    +
    df.groupby("MSISDN/Number")[
        "Youtube UL (Bytes)"
    ].sum().values
)


user_overview["Netflix Traffic"] = (
    df.groupby("MSISDN/Number")[
        "Netflix DL (Bytes)"
    ].sum().values
    +
    df.groupby("MSISDN/Number")[
        "Netflix UL (Bytes)"
    ].sum().values
)


user_overview["Gaming Traffic"] = (
    df.groupby("MSISDN/Number")[
        "Gaming DL (Bytes)"
    ].sum().values
    +
    df.groupby("MSISDN/Number")[
        "Gaming UL (Bytes)"
    ].sum().values
)


user_overview["Other Traffic"] = (
    df.groupby("MSISDN/Number")[
        "Other DL (Bytes)"
    ].sum().values
    +
    df.groupby("MSISDN/Number")[
        "Other UL (Bytes)"
    ].sum().values
)


# ------------------------------------------------------------
# 11. DISPLAY USER OVERVIEW
# ------------------------------------------------------------

print("\n===== USER OVERVIEW =====")

print(
    user_overview.head(10)
)


print("\nNumber of customers:",
      user_overview["MSISDN/Number"].nunique())


# ------------------------------------------------------------
# 12. TOP 10 HANDSETS
# ------------------------------------------------------------

top_10_handsets = (
    df["Handset Type"]
    .value_counts()
    .head(10)
)

print("\n===== TOP 10 HANDSETS =====")
print(top_10_handsets)


# ------------------------------------------------------------
# 13. TOP 3 HANDSET MANUFACTURERS
# ------------------------------------------------------------

top_3_manufacturers = (
    df["Handset Manufacturer"]
    .value_counts()
    .head(3)
)

print("\n===== TOP 3 HANDSET MANUFACTURERS =====")
print(top_3_manufacturers)


# ------------------------------------------------------------
# 14. TOP 5 HANDSETS FOR EACH TOP MANUFACTURER
# ------------------------------------------------------------

top_manufacturers = (
    top_3_manufacturers.index
)

top_5_per_manufacturer = (
    df[
        df["Handset Manufacturer"].isin(
            top_manufacturers
        )
    ]
    .groupby(
        [
            "Handset Manufacturer",
            "Handset Type"
        ]
    )
    .size()
    .reset_index(
        name="Count"
    )
    .sort_values(
        [
            "Handset Manufacturer",
            "Count"
        ],
        ascending=[
            True,
            False
        ]
    )
    .groupby(
        "Handset Manufacturer"
    )
    .head(5)
)

print("\n===== TOP 5 HANDSETS BY MANUFACTURER =====")

print(
    top_5_per_manufacturer
)


# ------------------------------------------------------------
# 15. SAVE CLEAN DATA
# ------------------------------------------------------------

df.to_csv(
    "/content/cleaned_telecom_data.csv",
    index=False
)


# ------------------------------------------------------------
# 16. SAVE USER OVERVIEW
# ------------------------------------------------------------

user_overview.to_csv(
    "/content/user_overview.csv",
    index=False
)


print("\n======================================")
print("TASK 1 DATA PREPARATION COMPLETED")
print("======================================")

print(
    "Cleaned data saved as:"
    "/content/cleaned_telecom_data.csv"
)

print(
    "User overview saved as:"
    "/content/user_overview.csv"
)